### ISSUE TITLE
x,y,z

### ISSUE THREAD

**Issue by robinfays12** [aimagelab/human-pose-annotation-tool#3]
Hello,

Thanks for this code. I would like to use the z position as well. Do you know how can I get it ? I guess somewhere in the "watch-n-patch.py" in the def get_joints_rgb.

Thanks for your help !

Robin

**Comment by Deusy94** [comment]
Hello, thank you for reaching out!

You can see in the Datasets.py that, for each split, the body joints are extracted for the depth frame using the function get_joints:

`patch_joints = {**patch_joints, **watch_n_patch.get_joints(os.path.join(root_dir, PATCH, "kitchen", el[0]))}` 

Since the keypoints list extracted is related to the depth frame, you can use such coordinates to get the z-value from the depth-map, with something like:

`img = scipy.io.loadmat(name)['depth']`
`kpts = [i for i in self.joints[name].values()]`
`z = np.array([img[int(k[1]) if int(k[1]) < img.shape[0] else img.shape[0] - 1,int(k[0]) if int(k[0]) < img.shape[1] else img.shape[1] - 1] for k in kpts])`

Note that you have to check if the starting noted values are in a correct range, since it's very probable that some kinect annotations are so bad that are out from the image!

I hope this helps!

**Comment by robinfays12** [comment]
Hello,

Wow, thanks for your answer dude, I'll try it ASAP.

K.R.,

Robin

**Comment by Deusy94** [comment]
I guess the problem was solved, if you need more help please reach out or open another issue!
Cheers.
